# https://github.com/elastic/elasticsearch-docker
FROM elasticsearch:5.5.1

# Add your elasticsearch plugins setup here
RUN elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v5.5.1/elasticsearch-analysis-ik-5.5.1.zip
