version: '2'

services:

  elasticsearch:
    build: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms14g -Xmx14g"
    networks:
      - elk


  cerebro:
    image: yannart/cerebro
    ports:
      - "9000:9000"
    networks:
      - elk


  kibana:
    build: kibana/
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch



networks:
  elk:
    driver: bridge
